### ISSUE TITLE
[feat] api => 缺少时间筛选参数

### ISSUE THREAD

**Issue by WayneVN** [embrace-century/blackhole#18]
```
https://api.basin.1hole.cn/api/layers/nodes?zoom=15&rectangle=%7B%22left_top_x%22:114.37083051577667,%22left_top_y%22:30.47267519150286,%22right_bottom_x%22:114.39619348422207,%22right_bottom_y%22:30.49059398385596%7D
```
该接口需要传时间来筛选数据用于(融合|对比)模式

**Comment by w-zengtao** [comment]
陈明贤弟这个 API 应该贴错了 

应该是监测点才对  

https://api.basin.1hole.cn/api/layers/node_monitors?zoom=15&rectangle=%7B%22left_top_x%22:114.37083051577667,%22left_top_y%22:30.47267519150286,%22right_bottom_x%22:114.39619348422207,%22right_bottom_y%22:30.49059398385596%7D
