### ISSUE TITLE
[feat]: 补全接口查询条件

### ISSUE THREAD

**Issue by WayneVN** [embrace-century/blackhole#19]
```
[GET] admin/rbacs/roles  // 添加 name 模糊查询
[GET] admin/rbacs/permissions // 添加 method/name/type 3个字段查询
[GET] admin/rbacs/policies // 添加 name 模糊查询
[GET] admin/staffs // 添加 name/email/gender 3个字段查询
```

**Comment by WayneVN** [comment]
```
[GET] admin/staffs // 返回当前用户所属roles => 返回整个 role对象给我
```

**Comment by seeown** [comment]
{{basin-host}}/admin/rbacs/roles?name="火箭"
{{basin-host}}/admin/rbacs/permissions?name="admin"&type="Api"&method="POST"
{{basin-host}}/admin/rbacs/policies?name="吹牛逼小组"
{{basin-host}}/admin/staffs?name="cm"&email="163"

**Comment by seeown** [comment]
> ```
> [GET] admin/staffs // 返回当前用户所属roles => 返回整个 role对象给我
> ```

{{basin-host}}/admin/staffs/2/roles
